app/blueprints/news/models.py
"""
Moduł definiuje modele bazy danych dla artykułów kryminalnych oraz powiązanych z nimi obrazów.
"""

from sqlalchemy import ForeignKey
from config import db


class CrimeNews(db.Model):
    """ Model reprezentujący artykuły kryminalne w bazie danych. """

    __tablename__ = 'crime_news'

    id = db.Column(db.Integer, primary_key=True)  # Klucz główny, unikalne id artykułu
    title = db.Column(db.String(255), nullable=False)  # Tytuł artykułu, pole wymagane
    summary = db.Column(db.Text, nullable=False)  # Streszczenie artykułu, pole wymagane
    description = db.Column(db.Text, nullable=True)  # Opis artykułu, pole opcjonalne
    image_url = db.Column(db.String(255), nullable=True)  # URL do obrazu, pole opcjonalne
    article_link = db.Column(db.String(255), nullable=False)  # URL do artykułu, wymagany
    publication_date = db.Column(db.Date, nullable=False)  # Data publikacji, wymagana


class CrimeImage(db.Model):
    """ Model reprezentujący obrazy związane z artykułami kryminalnymi. """
    # Nazwa tabeli w bazie danych
    __tablename__ = 'crime_images'

    id = db.Column(db.Integer, primary_key=True)  # Klucz główny, unikalne id obrazu
    image_url = db.Column(db.String(255), nullable=True)  # URL do obrazu, opcjonalny
    news_id = db.Column(db.Integer, ForeignKey('crime_news.id'), nullable=False)
    # Klucz obcy wskazujący na tabelę 'crime_news', pole wymagane

app/blueprints/news/routes.py
"""
Moduł zawierający routes dla modułu news.
"""

from flask import Blueprint, render_template, request
from sqlalchemy import desc
from config import db
from .models import CrimeNews, CrimeImage


news_bp = Blueprint(
    'news_bp',
    __name__,
    static_folder='static',
    template_folder='templates'
)


@news_bp.route('/')
def news_home():
    """ Główna strona z artykułami """
    per_page = 5  # Liczba artykułów wyświetlanych na jednej stronie
    page = request.args.get('page', 1, type=int)  # Pobranie numeru strony
    # Paginacja artykułów, sortowanie według daty publikacji (od najnowszych)
    paginated_articles = CrimeNews.query \
        .order_by(desc(CrimeNews.publication_date)) \
        .paginate(page=page, per_page=per_page, error_out=False)

    # Renderowanie szablonu z artykułami
    return render_template('news.html', articles=paginated_articles)


@news_bp.route('/<int:news_id>')
def single_news(news_id):
    """ Pojedynczy artykuł """
    # Pobranie artykułu na podstawie jego ID
    news = db.session.get(CrimeNews, news_id)

    # Jeśli artykuł nie istnieje, wyświetlamy komunikat o błędzie
    if news is None:
        return render_template(
            'single_news.html',
            news=None,
            images=None,
            error="Artykuł o podanym ID nie istnieje lub został usunięty."
        )

    # Pobranie obrazów powiązanych z danym artykułem
    images = CrimeImage.query.filter_by(news_id=news_id).all()

    # Renderowanie szablonu szczegółów artykułu
    return render_template('single_news.html', news=news, images=images)


@news_bp.route('/news_preview')
def news_preview():
    """ Widget wiadomości """
    # Pobranie 5 najnowszych artykułów
    latest_articles = CrimeNews.query \
        .order_by(CrimeNews.publication_date.desc()) \
        .limit(5)

    # Renderowanie szablonu karuzeli dla najnowszych artykułów
    return render_template('news_preview.html', articles=latest_articles)

app/blueprints/news/templates/news.html
{% extends "base.html" %} 

{% block title %}Wiadomości kryminalne{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/news.css') }}"/>

    <script>
      function openModal(imageSrc) {
        const modal = document.getElementById("image-modal");
        const modalImage = document.getElementById("modal-image");
        modalImage.src = imageSrc;
        modal.style.display = "flex";
      }
    
      function closeModal() {
        const modal = document.getElementById("image-modal");
        modal.style.display = "none";
      }
    </script>

    
    {% endblock %} {%block main %}
    <div class="container mt-4">
      <h1 class="text-center mb-4">Wiadomości kryminalne dla Krakowa</h1>
      {% if error %}
      <div class="alert alert-danger">{{ error }}</div>
      {% else %}
      
        <table class="table table-striped">
          <tbody>
            {% for article in articles %}
            <tr>
              <td class="image-cell">
                <img
                  src="{{article.image_url}}" 
                  referrerpolicy="no-referrer"
                  alt="Zdjęcie"
                  class="article-image"
                  onclick="openModal('{{ article.image_url }}')"
                />
              </td>
              <td class="summary">
                <strong>
                  <a href="{{ url_for('news_bp.single_news', news_id=article.id) }}">
                  {{ article.title }}
                  </a>
                </strong>
                <br>
                {{ article.summary }}
                <br>
                <br>
                <span class="data">Data publikacji: {{article.publication_date.strftime('%d.%m.%Y')}}</span>
                <span class="source">Źródło: policja.pl</span>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <nav aria-label="Page navigation" class='pagination-container'>
          <ul class="pagination">
              <li class="page-item {% if articles.page == 1 %}disabled{% endif %}">
                  <a class="page-link" href="{{ url_for('news_bp.news_home') }}?page=1">Pierwsza</a>
              </li>
              <li class="page-item {% if articles.page == 1 %}disabled{% endif %}">
                  <a class="page-link" href="{{ url_for('news_bp.news_home') }}?page={{ articles.page - 1 }}">Poprzednia</a>
              </li>
              <li class="page-item {% if articles.page == articles.pages %}disabled{% endif %}">
                  <a class="page-link" href="{{ url_for('news_bp.news_home') }}?page={{ articles.page + 1 }}">Następna</a>
              </li>
              <li class="page-item {% if articles.page == articles.pages %}disabled{% endif %}">
                  <a class="page-link" href="{{ url_for('news_bp.news_home') }}?page={{ articles.pages }}">Ostatnia</a>
              </li>
          </ul>
      </nav>

      {% endif %}
    </div>

    <a href="{{ url_for('main_bp.main') }}" class="btn btn-primary sticky-back-button">Powrót</a>
    <div
      id="image-modal"
      class="modal-overlay"
      style="display: none"
      onclick="closeModal()"
    >

      <img id="modal-image" class="modal-image" alt="Powiększone zdjęcie" />
    </div>
    
    {% endblock %}

app/blueprints/news/templates/news_preview.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/news_preview.css') }}"/>
</head>
<body>
    <div id="newsCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            {% if articles %}
                {% for article in articles %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img src="{{ article.image_url }}" class="d-block w-100" alt="{{ article.title }}" referrerpolicy="no-referrer">
                        <div class="carousel-caption">
                            <a href="{{ url_for('news_bp.single_news', news_id=article.id) }}" target="_top">
                                <h3>{{article.title}}</h3>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-warning">Brak artykułów do wyświetlenia.</div>
            {% endif %}
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#newsCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#newsCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <script>
        const newsCarouselElement = document.querySelector('#newsCarousel');
        const carousel = new bootstrap.Carousel(newsCarouselElement, {
            interval: 4000,
        });
    </script>
</body>
</html>

app/blueprints/news/templates/single_news.html
{% extends "base.html" %}
{% block title %}{{ news.title }}{% endblock %}

{% block header %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/single_news.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/news.css') }}"/>

<script>
    function openModal(imageSrc) {
      const modal = document.getElementById("image-modal");
      const modalImage = document.getElementById("modal-image");
      modalImage.src = imageSrc;
      modal.style.display = "flex";
    }
  
    function closeModal() {
      const modal = document.getElementById("image-modal");
      modal.style.display = "none";
    }
  </script>

{% endblock %}

{% block main %}
<div class="container mt-4">
    {% if error %}
    <div class="alert alert-warning">
        {{ error }}
    </div>
    {% else %}
    <h1 class="news-title">{{ news.title }}</h1>
    <p class="publication-date">Data publikacji: {{ news.publication_date.strftime('%d.%m.%Y') }}
        <br>Źródło: policja.pl
    </p>

    <hr class="divider">
    
    <div class="news-content">
        <img src="{{ news.image_url }}" alt="Zdjęcie" class="main-news-image" referrerpolicy="no-referrer">
        <p class="summary-text">{{ news.summary }}</p>
        <p class="news-text">{{ news.description }}</p>
    </div>

    {% if images %}
    <div class="image-gallery">
        <h3>Galeria</h3>
        <div class="gallery-grid">
            {% for image in images %}
            <div class="gallery-item">
                <img src="{{ image.image_url }}" alt="Zdjęcie" class="gallery-image" referrerpolicy="no-referrer"  onclick="openModal('{{ image.image_url }}')">
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% endif %}
</div>

<a href="{% if not request.referrer %}{{ url_for('news_bp.news_home') }}{% elif 'news_preview' in request.referrer %}{{ url_for('main_bp.main') }}{% else %}{{ request.referrer }}{% endif %}"   class="btn btn-primary sticky-back-button">Powrót</a>
<div
    id="image-modal"
    class="modal-overlay"
    style="display: none"
    onclick="closeModal()"
>
    
    <img id="modal-image" class="modal-image" alt="Powiększone zdjęcie" />
</div>

{% endblock %}