app/blueprints/sport/models.py
from config import db
from datetime import datetime

class SportArticle(db.Model):
    __tablename__ = 'sport_articles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=True)
    image_url = db.Column(db.String(255), nullable=True)
    pubDate = db.Column(db.DateTime, nullable=True)
    link = db.Column(db.String(255), nullable=True)
    sport_type = db.Column(db.String(50), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f'<SportArticle {self.title}>'

app/blueprints/sport/routes.py
from flask import Blueprint, render_template, request
import requests
from .models import SportArticle
from config import db
from datetime import datetime

sport_bp = Blueprint(
    'sport',
    __name__,
    static_folder='static',
    template_folder='templates'
)

SPORT_API = {
    "football": "https://newsdata.io/api/1/news?apikey=pub_593496808acfb9d29e8410845a3b9602f5863&q=piłka%20nożna&country=pl&category=sports",
    "tennis": "https://newsdata.io/api/1/news?apikey=pub_593496808acfb9d29e8410845a3b9602f5863&q=tenis&country=pl&category=sports",
    "ski_jumping": "https://newsdata.io/api/1/news?apikey=pub_593496808acfb9d29e8410845a3b9602f5863&q=skoki%20narciarskie&country=pl&category=sports",
    "volleyball": "https://newsdata.io/api/1/news?apikey=pub_593496808acfb9d29e8410845a3b9602f5863&q=siatkówka&country=pl&category=sports"
}

@sport_bp.route('/')
def sport_home():
    sport_names = {
        "football": "Piłka nożna",
        "tennis": "Tenis",
        "ski_jumping": "Skoki narciarskie",
        "volleyball": "Siatkówka"
    }
    selected_discipline = request.args.get('discipline')

    page = request.args.get('page', 1, type=int)
    per_page = 5

    if selected_discipline:
        articles = SportArticle.query.filter_by(sport_type=selected_discipline).order_by(SportArticle.pubDate.desc()).paginate(page=page, per_page=per_page)
    else:
        articles = SportArticle.query.order_by(SportArticle.pubDate.desc()).paginate(page=page, per_page=per_page)
    
    return render_template('sport.html', articles=articles, sport_names=sport_names)

def fetch_and_save_articles():
    from app import app
    with app.app_context():
        for sport_type, api_url in SPORT_API.items():
            response = requests.get(api_url)
            if response.status_code == 200:
                data = response.json()
                for article in data.get("results", []):
                    existing_article = SportArticle.query.filter_by(title=article.get("title")).first()
                    if not existing_article:
                        pub_date_str = article.get("pubDate")
                        pub_date = datetime.strptime(pub_date_str, "%Y-%m-%d %H:%M:%S") if pub_date_str else None
                        
                        new_article = SportArticle(
                            title=article.get("title"),
                            description=article.get("description"),
                            image_url=article.get("image_url"),
                            pubDate=pub_date,
                            link=article.get("link"),
                            sport_type=sport_type
                        )
                        db.session.add(new_article)
                db.session.commit()
            

@sport_bp.route('/sport_preview')
def sport_preview():
    disciplines = ['football', 'tennis', 'ski_jumping', 'volleyball']
    articles = []
    
    for discipline in disciplines:
        article = SportArticle.query.filter_by(sport_type=discipline).order_by(SportArticle.pubDate.desc()).first()
        if article:
            articles.append(article)

    sport_names = {
        'football': 'Piłka Nożna',
        'tennis': 'Tenis',
        'ski_jumping': 'Skoki Narciarskie',
        'volleyball': 'Siatkówka',
    }

    return render_template('sport_preview.html', articles=articles, sport_names=sport_names)

app/blueprints/sport/templates/sport.html
{% extends "base.html" %} {% block title %}Sport{% endblock %} {% block header
%}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/sport.css') }}"
/>
<script>
  function openModal(imageSrc) {
    const modal = document.getElementById("image-modal");
    const modalImage = document.getElementById("modal-image");
    modalImage.src = imageSrc;
    modal.style.display = "flex";
  }

  function closeModal() {
    const modal = document.getElementById("image-modal");
    modal.style.display = "none";
  }
</script>
{% endblock %} {% block main %} {% with messages =
get_flashed_messages(with_categories=true) %} {% if messages %}
<div class="flashes">
  {% for category, message in messages %}
  <div class="alert alert-{{ category }}">{{ message }}</div>
  {% endfor %}
</div>
{% endif %} {% endwith %}
<div class="container mt-4">
  <h1 class="text-center mb-4">Najnowsze artykuły sportowe!</h1>
  <div class="filter-buttons">
    <form action="{{ url_for('sport.sport_home') }}" method="get">
      <button
        type="submit"
        name="discipline"
        value="football"
        class="btn btn-primary mx-2"
      >
        Piłka nożna
      </button>
      <button
        type="submit"
        name="discipline"
        value="tennis"
        class="btn btn-primary mx-2"
      >
        Tenis
      </button>
      <button
        type="submit"
        name="discipline"
        value="ski_jumping"
        class="btn btn-primary mx-2"
      >
        Skoki Narciarskie
      </button>
      <button
        type="submit"
        name="discipline"
        value="volleyball"
        class="btn btn-primary mx-2"
      >
        Siatkówka
      </button>
      <button
        type="submit"
        name="discipline"
        value=""
        class="btn btn-secondary mx-2"
      >
        Usuń
      </button>
    </form>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Zdjęcie</th>
          <th>Tytuł</th>
          <th>Opis</th>
          <th>Data</th>
          <th>Dyscyplina</th>
          <th>Link</th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles %}
        <tr>
          <td>
            {% if article.image_url %}
            <img
              src="{{ article.image_url }}"
              alt="Article photo"
              class="article-image"
              onclick="openModal('{{ article.image_url }}')"
            />
            {% else %} Brak zdjęcia {% endif %}
          </td>
          <td><strong>{{ article.title }}</strong></td>
          <td>
            {% if article.description %} {{ article.description }} {% else %}
            Opis niedostępny - przejdź do pełnego artykułu -> {% endif %}
          </td>
          <td>
            {% if article.pubDate %} {{ article.pubDate.strftime('%Y-%m-%d
            %H:%M:%S') }} {% else %} Brak daty {% endif %}
          </td>

          <td>{{ sport_names[article.sport_type] }}</td>
          <td>
            {% if article.link %}
            <a href="{{ article.link }}" target="_blank" class="btn btn-link"
              >Czytaj więcej</a
            >
            {% else %} Brak linku {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <nav aria-label="Page navigation" class="pagination-container">
      <ul class="pagination">
        <li class="page-item {% if articles.page == 1 %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for('sport.sport_home', page=1) }}"
            >Pierwsza</a
          >
        </li>
        <li class="page-item {% if articles.page == 1 %}disabled{% endif %}">
          <a
            class="page-link"
            href="{{ url_for('sport.sport_home', page=articles.page - 1) }}"
            >Poprzednia</a
          >
        </li>
        <li
          class="page-item {% if articles.page == articles.pages %}disabled{% endif %}"
        >
          <a
            class="page-link"
            href="{{ url_for('sport.sport_home', page=articles.page + 1) }}"
            >Następna</a
          >
        </li>
        <li
          class="page-item {% if articles.page == articles.pages %}disabled{% endif %}"
        >
          <a
            class="page-link"
            href="{{ url_for('sport.sport_home', page=articles.pages) }}"
            >Ostatnia</a
          >
        </li>
      </ul>
    </nav>
  </div>
  <div>
    <a
      href="{{ url_for('main_bp.main') }}"
      class="btn btn-primary sticky-back-button"
      >Powrót</a
    >
  </div>
  <div
    id="image-modal"
    class="modal-overlay"
    style="display: none"
    onclick="closeModal()"
  >
    <img id="modal-image" class="modal-image" alt="Enlarged photo" />
  </div>
  {% endblock %}
</div>

app/blueprints/sport/templates/sport_preview.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/news_preview.css') }}"
    />
    <title>Sport Preview</title>
  </head>
  <body>
    <div id="sportCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        {% if articles %} {% for article in articles %}

        <div class="carousel-item {% if loop.first %}active{% endif %}">
          <img
            src="{{ article.image_url }}"
            class="d-block w-100"
            alt="{{ article.title }}"
            referrerpolicy="no-referrer"
          />
          <div class="carousel-caption">
            <a href="{{ article.link }}" target="_top">
              <h3>{{article.title}}</h3>
            </a>
          </div>
        </div>
        {% endfor %} {% else %}
        <div class="alert alert-warning">Brak artykułów do wyświetlenia.</div>
        {% endif %}
      </div>

      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#sportCarousel"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#sportCarousel"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <script>
      const sportCarouselElement = document.querySelector("#sportCarousel");
      const carousel = new bootstrap.Carousel(sportCarouselElement, {
        interval: 5000,
      });
    </script>
  </body>
</html>